name: Release

on: [workflow_dispatch]

jobs:
  release:
    name: release
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - uses: softprops/action-gh-release@v1
        with:
          files: target/release/win32yank.exe
          tag_name: latest
          generate_release_notes: true
